version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=fastnotesdb;Username=postgres;Password=postgres

  ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ui
    ports:
      - "3000:80"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: fastnotesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
