# Используем SDK-образ для сборки
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY FastNotes.Api/*.csproj FastNotes.Api/
COPY FastNotes.Shared/*.csproj FastNotes.Shared/

RUN dotnet restore FastNotes.Api/FastNotes.Api.csproj

COPY . .
WORKDIR /src/FastNotes.Api
RUN dotnet publish -c Release -o /app/publish

# Используем runtime-образ
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "FastNotes.Api.dll"]
